### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mwprado**
sip import module has changed location after sip rpm replaced python3-sip.

### CODE REVIEW

**Comment by kwizart** [comment]
Please consider to forward this issue to bugzilla.rpmfusion.org if not done already.

**Comment by mwprado** [comment]
Issue created on bugzilla:
https://bugzilla.rpmfusion.org/show_bug.cgi?id=5502

**Comment by sergiomb2** [comment]
pleas close this pr (if it solved ) , I haven't permissions

**Comment by kwizart** [comment]
rfbz fixed, so closing

**Pull request closed without merging**
